### ISSUE TITLE
extension translations

### ISSUE THREAD

**Issue by jnweiger** [Neon22/inkscape_extension_template#4]
Is there a way to provide translations that ship with an extension?
I give my workshops in german, but want to code in english.

All I could find are inkscape.mo files being loaded. Does that mean that all extension texts must be combined into one single inkscape.mo file?

**Comment by Moini** [comment]
The only way I've found used, which definitely works without compiling, would be to do the same as here:
https://github.com/giacmir/Inkscape-JPEG-export-extension/tree/master/translations
(it provides separate inx files for each language. If you have relevant error messages in the python code, you /could/ make it pull the translations in dynamically, or also provide separate files).

I do not know if it would be possible to do this 'correctly' with a separate po file, I only know about the workaround others use. You'd better ask on the developer mailing list if the workaround isn't feasible for you.

**Comment by jnweiger** [comment]
Ah haven't though of this simple workaround. Should work fine for me too. Thanks!

**Comment by Moini** [comment]
@Neon22 has asked on the mailing list about this, didn't know if you knew (from your answer, I gather you don't):
https://sourceforge.net/p/inkscape/mailman/message/35790138/

**Comment by jnweiger** [comment]
Saw this. Trying to subscribe to inkscape-devel. Thanks!
