### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by YoSarin** [Neon22/inkscape_extension_template#6]
https://github.com/Neon22/inkscape_extension_template/blob/4889dc92b21a9ad928a4b390e1d90209ab5678df/template.py#L295

I guess you shall call .effect() here, not .affect(), rright?

**Comment by Neon22** [comment]
nope.
check other .py extensions to see them all using .affect

**Comment by YoSarin** [comment]
You're obviously right. Just was coming back to state that I'm wrong, sorry...
On the other hand - it would be great if it would be explicitly stated in example code. :)

**Comment by Neon22** [comment]
yes. I got stuck when I first strated writing them. I think its defined in the inkex.py file
Not totally sure. Probably a grammar wonk who knows that Effect describes what an effect does and Affect means to act directly on something.
